
#Font color
alias green='echo -e "Default \e[32mGreen"'
alias black='echo -e "Default \e[30mBlack"'
alias red='echo -e "Default \e[31mRed"'
alias yellow='echo -e "Default \e[33mYellow"'
alias blue=' echo -e "Default \e[34mBlue"'
alias magenta='echo -e "Default \e[35mMagenta"'
alias cyan='echo -e "Default \e[36mCyan"'
alias lgray='echo -e "Default \e[37mLight gray"'
alias dgray='echo -e "Default \e[90mDark gray"'
alias lred='echo -e "Default \e[91mLight red"'
alias lgreen='echo -e "Default \e[92mLight green"'
alias lyellow='echo -e "Default \e[93mLight yellow"'
alias lblue='echo -e "Default \e[94mLight blue"'
alias lmagenta='echo -e "Default \e[95mLight magenta"'
alias lcyan='echo -e "Default \e[96mLight cyan"'
#Background color
alias bblack='echo -e "Default \e[40mBlack"'
alias bred='echo -e "Default \e[41mRed"'
alias bgreen='echo -e "Default \e[42mGreen"'
alias byellow='echo -e "Default \e[43mYellow"'
alias bblue='echo -e "Default \e[44mBlue"'
alias bmagenta='echo -e "Default \e[45mMagenta"'
alias bcyan='echo -e "Default \e[46mCyan"'
alias blgray='echo -e "Default \e[47mLight gray"'
alias bdgray='echo -e "Default \e[100mDark gray"'
alias blred='echo -e "Default \e[101mLight red"'
alias blgreen='echo -e "Default \e[102mLight green"'
alias blyellow='echo -e "Default \e[103mLight yellow"'
alias blblue='echo -e "Default \e[104mLight blue"'
alias blmagent='echo -e "Default \e[105mLight magenta"'
alias blcyan='echo -e "Default \e[106mLight cyan"'
alias bwhite='echo -e "Default \e[107mWhite"'
